import type { PrintTemplate } from "../types";

export const PRINT_TEMPLATES: PrintTemplate[] = [
  {
    id: "luxury-gold",
    name: "Luxury Gold",
    category: "Luxury",
    description: "Opulent cream with gold double-rule border and ornate corner flourishes.",
    primaryBg: "#FAF6EE",
    primaryText: "#1A1007",
    accentColor: "#C9A96E",
    mutedText: "#8A7455",
    borderColor: "#C9A96E",
  },
  {
    id: "classic-ivory",
    name: "Classic Ivory",
    category: "Classic",
    description: "Timeless ivory with fine black rule and graceful serif typography.",
    primaryBg: "#FFFFF0",
    primaryText: "#111111",
    accentColor: "#111111",
    mutedText: "#555555",
    borderColor: "#111111",
  },
  {
    id: "minimalist",
    name: "Minimalist",
    category: "Minimalist",
    description: "Pure white canvas with generous white-space and clean sans-serif type.",
    primaryBg: "#FFFFFF",
    primaryText: "#1A1A1A",
    accentColor: "#1A1A1A",
    mutedText: "#888888",
    borderColor: "#DDDDDD",
  },
  {
    id: "floral-garden",
    name: "Floral Garden",
    category: "Floral",
    description: "Soft sage background with botanical corner accents and warm gold text.",
    primaryBg: "#F2F4EE",
    primaryText: "#2D3A1E",
    accentColor: "#7A9E5B",
    mutedText: "#5C6B4A",
    borderColor: "#9CB97A",
  },
  {
    id: "royal-burgundy",
    name: "Royal Burgundy",
    category: "Royal",
    description: "Deep jewel-toned background with luminous gold text and double-gilt frame.",
    primaryBg: "#3B0D1A",
    primaryText: "#F5E6C8",
    accentColor: "#C9A96E",
    mutedText: "#C2A87A",
    borderColor: "#C9A96E",
  },
  {
    id: "african-gold",
    name: "African Gold",
    category: "African",
    description: "Rich terracotta inspired by traditional Kente — bold, warm and celebratory.",
    primaryBg: "#7B3318",
    primaryText: "#FFE599",
    accentColor: "#FFD700",
    mutedText: "#FFCC66",
    borderColor: "#FFD700",
  },
  {
    id: "beach-bliss",
    name: "Beach Bliss",
    category: "Beach",
    description: "Airy gradient of sky and sea with ocean-blue accents — relaxed elegance.",
    primaryBg: "#EBF5FB",
    primaryText: "#0D3B52",
    accentColor: "#2E86AB",
    mutedText: "#4A8EAA",
    borderColor: "#7EC8E3",
  },
  {
    id: "vintage-romance",
    name: "Vintage Romance",
    category: "Vintage",
    description: "Aged parchment with sepia tones and filigree ornaments — nostalgic charm.",
    primaryBg: "#F4EDD7",
    primaryText: "#3B2A14",
    accentColor: "#8B6914",
    mutedText: "#7A5C2E",
    borderColor: "#C4A55A",
  },
  {
    id: "midnight-glamour",
    name: "Midnight Glamour",
    category: "Modern",
    description: "Dramatic matte black with gilded type and neon-thin gold rule.",
    primaryBg: "#111111",
    primaryText: "#F0D080",
    accentColor: "#C9A96E",
    mutedText: "#B8975A",
    borderColor: "#C9A96E",
  },
];

export const PRINT_CATEGORIES = [
  "All", "Luxury", "Classic", "Minimalist", "Floral",
  "Royal", "African", "Modern", "Beach", "Vintage",
];
